export declare const Z_INDEX_CALENDAR_CONTAINER: number;
export declare const XS_SCREEN = "24em";
export declare const SM_SCREEN = "35.5em";
export declare const MD_SCREEN = "48em";
export declare const MD_SCREEN_PLUS_ONE = "769px";
export declare const LG_SCREEN = "56em";
export declare const LG_SCREEN_PLUS_ONE = "897px";
export declare const XL_SCREEN_MINUS_ONE = "1023px";
export declare const XL_SCREEN = "64em";
export declare const XXL_SCREEN = "80em";
export declare const XXL_SCREEN_MINUS_ONE = "1279px";
export declare const CENTERED_CONTAINER_WIDTH = 1440;
export declare const INSTITUTIONAL_CONTENT_WIDTH = 1140;
export declare const MAX_TEXT_WIDTH = 700;
export declare const MINW_XS_SCREEN: string;
export declare const MINW_SM_SCREEN: string;
export declare const MINW_MD_SCREEN: string;
export declare const MINW_MD_SCREEN_PLUS_ONE: string;
export declare const MINW_LG_SCREEN: string;
export declare const MINW_LG_SCREEN_PLUS_ONE: string;
export declare const MINW_XL_SCREEN: string;
export declare const MINW_XXL_SCREEN: string;
export declare const MINW_CENTERED_CONTAINER_WIDTH: string;
export declare const MINW_INSTITUTIONAL_CONTENT_WIDTH: string;
export declare const MAXW_XS_SCREEN: string;
export declare const MAXW_SM_SCREEN: string;
export declare const MAXW_MD_SCREEN: string;
export declare const MAXW_MD_SCREEN_PLUS_ONE: string;
export declare const MAXW_LG_SCREEN: string;
export declare const MAXW_LG_SCREEN_PLUS_ONE: string;
export declare const MAXW_XL_SCREEN: string;
export declare const MAXW_XL_SCREEN_MINUS_ONE: string;
export declare const MAXW_XXL_SCREEN: string;
export declare const MAXW_XXL_MINUS_ONE_SCREEN: string;
export declare const MAXW_CENTERED_CONTAINER_WIDTH: string;
export declare const MAXW_INSTITUTIONAL_CONTENT_WIDTH: string;
