export declare const months: any;
export declare const defaultClasses: {
    calendar: string;
    dateRange: string;
    predefinedRanges: string;
    predefinedRangesItem: string;
    predefinedRangesItemActive: string;
    monthAndYear: string;
    weekDays: string;
    weekDay: string;
    days: string;
    day: string;
    dayWrapper: string;
    dayActive: string;
    dayPassive: string;
    dayInRange: string;
    dayStartEdge: string;
    dayEndEdge: string;
    dayToday: string;
    dayFromPreviousMonth: string;
    monthAndYearWrapper: string;
    prevButton: string;
    nextButton: string;
    month: string;
    monthAndYearDivider: string;
    year: string;
    daySunday: string;
    daySpecialDay: string;
};
